skeleton/config/routes.rb
Links::Application.routes.draw do

  resources :users
  resources :posts
  resources :links
  resource :session
  resources :comments, only: [:create, :destroy]

end

skeleton/app/models/comment.rb
class Comment < ActiveRecord::Base

  validates :body, presence: true

  belongs_to :link

end

skeleton/app/models/link.rb
class Link < ActiveRecord::Base

  validates :title, :url, presence: true

  has_many :comments

end

skeleton/app/models/user.rb
class User < ActiveRecord::Base

  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  #TODO

  attr_reader :password
  #TODO don't forget this

  has_many :links


  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return nil if user.nil?
    user.is_password?(password)? user : nil
    #TODO no space after ? for ternary!
  end

  def password=(password)
    @password = password
    self.password_digest=BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def reset_session_token
    token = SecureRandom.urlsafe_base64(16)
    self.session_token = token
    self.save!
    token
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
  #TODO must have or spec fails. can't save user.

end

skeleton/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def sign_in(user)
    session[:session_token] = user.reset_session_token
    #had an erroneous @ for user here.
  end

  def current_user
    User.find_by(session_token: session[:session_token])
    # was assigning this to @user. big no-no. messed up whatever was already @user
  end

  def logged_in?
    !!current_user
  end



end

skeleton/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    comment = Comment.new(comment_params)
    comment.user_id = current_user.id
    comment.save
    flash[:errors] = comment.errors.full_messages
    link_id = params[:comment][:link_id]
    redirect_to link_url(link_id)
  end

  def destroy
    comment = Comment.find(params[:id])
    #id is in the PARAMS OF BUTTON
    comment.destroy
    redirect_to link_url(comment.link_id)
  end


  private

  def comment_params
    params.require(:comment).permit(:body, :user_id, :link_id)
  end

end

skeleton/app/controllers/links_controller.rb
class LinksController < ApplicationController

before_action :ensure_logged_in

  def index
    @links = Link.all
    render :index
  end

  def new
    @link = Link.new
    # this below will not work! TODO remember
    # @link ||= Link.new(link_params)
    render :new
  end

  def ensure_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def create
    @link = Link.new(link_params)
    @link.user_id = current_user.id
    #TODO don't forget that line above
    if @link.save
      redirect_to link_url(@link)
    else
      flash.now[:errors] = @link.errors.full_messages
      render :new
    end
  end

  def show
    @link = Link.find(params[:id])
    #how do we know at this point that id is in params? is it left over?
    #OH YEAH, it's part of the query string
    render :show
  end

  def edit
    @link = Link.find(params[:id])
    render :edit
  end


  def update
    @link = Link.find(params[:id])
    if @link.update(link_params)
      redirect_to link_url(@link)
    else
      flash.now[:errors] = @link.errors.full_messages
      render :edit
    end
  end

  private
  def link_params
    params.require(:link).permit(:title, :url)
  end

end

skeleton/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
    params[:user][:username],
    params[:user][:password]
    )
    if user.nil?
      flash.now[:errors] = ["Invalid username and/or password"]
      render :new
    else
      sign_in(user)
      redirect_to links_url
    end
  end

  def destroy
    user = User.find_by(session_token: session[:session_token])
    user.reset_session_token
    session[:sesison_token] = nil
    redirect_to new_session_url
  end


end

skeleton/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to links_url
      # Will get error below if you don't have links/index view created
    else
      flash.now[:errors] = @user.errors.full_messages
      #easy to forget that one
      render :new
    end
  end



  private
  def user_params
    params.require(:user).permit(:password, :username)
  end


end

skeleton/app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token_input
  "<input
      type=\"hidden\"
      name=\"authenticity_token\"
      value=\"#{ form_authenticity_token }\">".html_safe
end


end

skeleton/app/helpers/comments_helper.rb
module CommentsHelper
end

skeleton/app/helpers/links_helper.rb
module LinksHelper
end

skeleton/app/helpers/sessions_helper.rb
module SessionsHelper
end

skeleton/app/helpers/users_helper.rb
module UsersHelper
end

skeleton/app/views/layouts/_errors.html.erb
<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>

skeleton/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Links</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  <%= current_user.username %>
  <%= button_to "Sign Out", session_url, :method => :delete %>
<% else %>
  <%= link_to "Sign In", new_session_url %>
  <%= link_to "Sign Out", new_user_url %>
<% end %>


<%= render "layouts/errors" %>

<%= yield %>

</body>
</html>

skeleton/app/views/links/edit.html.erb
<h2>Edit Link</h2>

<form action="<%= link_url(@link) %>" method="POST">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token_input %>

  <label>
    Title
    <input type="text" name="link[title]" value="<%= @link.title %>" id="title">
  </label>

  <label>
    URL
    <input type="text" name="link[url]" value="<%= @link.url %>" id="url">
  </label>

  <input type="submit" value="Update Link">
</form>

skeleton/app/views/links/index.html.erb
<%= link_to("New Link", new_link_url) %>
<h1>ALL THE LINKS</h1>

<ul>
<% @links.each do |link| %>
  <li> <%= link_to(link.title, link_url(link)) %>
  </li>
<% end %>
</ul>

skeleton/app/views/links/new.html.erb
<h2>New Link</h2>

<form action="<%= links_url %>" method="post">
  <%= auth_token_input %>

  <label>
    Title
    <input type="text" name="link[title]" value="<%= @link.title %>" id="title">
  </label>

  <label>
    URL
    <input type="text" name="link[url]" value="<%= @link.url %>" id="url">
  </label>

  <input type="submit" value="Create New Link">
</form>

skeleton/app/views/links/show.html.erb
<h2><%= @link.title %></h2>
<%= @link.url %>
<%= link_to("Edit Link", edit_link_url(@link)) %>
<br>
<%=  link_to("Links", links_url) %>

<br>
<h2>Comments</h2>
<% @link.comments.each do |comment| %>
  <%= comment.body %>
  <%= button_to "Remove Comment", comment_url(comment), method: :delete %>
<% end %>


<form action="<%= comments_url %>" method="post">
  <%= auth_token_input %>
  <input type="hidden" name="comment[link_id]" value="<%= @link.id %>">
  <label>
    Add Comment
    <input type="text" name="comment[body]" value="">
  </label>

  <input type="submit" value="Add Comment">
</form>

skeleton/app/views/users/new.html.erb
<h2>Sign Up</h2>

<form action="<%= users_url %>" method="post">
  <%= auth_token_input %>
  <label>
    Username
    <input type="text" name="user[username]" value="">
  </label>

  <label>
    Password
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" value="Sign Up">
</form>